name: flutter_cross_platform
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  
  flutter:
    sdk: flutter
    
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^8.0.8
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
