// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnHoKjVZZzFNcCrbw6htLQGQJzIOfcePM',
    appId: '1:593310460173:web:6a54d72d961c47f2b02844',
    messagingSenderId: '593310460173',
    projectId: 'flutter-mvc-a6161',
    authDomain: 'flutter-mvc-a6161.firebaseapp.com',
    storageBucket: 'flutter-mvc-a6161.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NvkPtarDbH7VA-6-uEpB-1ukXYut8vs',
    appId: '1:593310460173:android:d5019b57760a2a57b02844',
    messagingSenderId: '593310460173',
    projectId: 'flutter-mvc-a6161',
    storageBucket: 'flutter-mvc-a6161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKogn_VR69kU768dB_hhAMgGV7Ws0jfaI',
    appId: '1:593310460173:ios:bcfe32eb156de759b02844',
    messagingSenderId: '593310460173',
    projectId: 'flutter-mvc-a6161',
    storageBucket: 'flutter-mvc-a6161.appspot.com',
    iosBundleId: 'com.example.flutterCrossPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKogn_VR69kU768dB_hhAMgGV7Ws0jfaI',
    appId: '1:593310460173:ios:ec798c6b0b3f20c4b02844',
    messagingSenderId: '593310460173',
    projectId: 'flutter-mvc-a6161',
    storageBucket: 'flutter-mvc-a6161.appspot.com',
    iosBundleId: 'com.example.flutterCrossPlatform.RunnerTests',
  );
}
